version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FIRESTORE_CREDENTIALS=/app/credentials/service-account.json
      - CORS_ORIGINS=http://localhost:5173,http://localhost:3000
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - ./backend:/app
      - ./credentials:/app/credentials
    command: uvicorn main:socket_app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis
    networks:
      - codeduel-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - codeduel-network

networks:
  codeduel-network:
    driver: bridge
